info:
    split_size: 0.3
    type: balanced
    method: ann
dataset:
    n_samples: 1000
    n_features: 100
    n_informative: 10
    n_classes: 5
training:
    epochs: 30
    valid_epochs: 10
    batch_size: 64
    shuffle: True
    num_workers: 8
wandb:
    project: inatc
    entity: kad99kev