info:
    split_size: 0.3
    type: balanced
    method: neat
    fitness_function: f1_score
dataset:
    n_samples: 1000
    n_features: 100
    n_informative: 10
    n_classes: 5
generations: 100
wandb:
    project: inatc
    entity: kad99kev