info:
    split_size: 0.3
    type: unbalanced
    method: neat
    fitness_function: f1_score
    model: vanilla
dataset:
    n_samples: 1000
    n_features: 100
    n_informative: 10
    n_classes: 5
    weights: [0.7, 0.125, 0.125, 0.025, 0.025]
generations: 100
wandb:
    project: inatc-toy
    entity: kad99kev